### ISSUE TITLE
Code in repository doesn't run

### ISSUE THREAD

**Issue by RichLinnell** [PacktPublishing/Ionic-2-Blueprints#2]
This is sort of a follow up to my earlier issue.  

I thought I would clone the repository and see if the same issues occurred with firebase not being found.  They don't, (I can see in the typings global that firebase3 is there in the project I created from scratch it's not), so there is clearly something changed in the setup that I have not been able to find online. (I have pushed up my "typed-in" version of the chapter's code to my own GitHub repo, you may be able to easily spot my error)

However, the project still doesn't run, but this time the only errors are :

TypeScript error: /Users/rdlinnell/Documents/Development/ionic/downloadedChat/Ionic-2-Blueprints/Chapter01/node_modules/angularfire2/angularfire2.d.ts(4,10): Error TS2305: Module '"/Users/rdlinnell/Documents/Development/ionic/downloadedChat/Ionic-2-Blueprints/Chapter01/node_modules/@angular/core/index"' has no exported member 'ModuleWithProviders'.
TypeScript error: app/app.ts(55,5): Error TS2345: Argument of type '{ provider: AuthProviders; method: AuthMethods; remember: string; scope: string[]; }' is not assignable to parameter of type 'AuthConfiguration'.
  Object literal may only specify known properties, and 'remember' does not exist in type 'AuthConfiguration'.

**Comment by ManikandanKurup-Packt** [comment]
Please reopen the issue if this error still exists. Thanks!
